ENVIRONMENTS = (
    ('sbx', 'Sandbox'),
    ('stg', 'Staging'),
    ('qar', 'QAR API'),
    ('qa58', 'QA58'),

)

API_HEADERS = [
    'Transaction Type',
    'Account Name',
    'Email Address',
    'OAuth Service',
    'IP Address',
    'Device Fingerprint',
    'Device Fingerprint Type',
    'Billing First Name',
    'Billing Middle Name',
    'Billing Last Name',
    'Billing Street',
    'Billing Country',
    'Billing Zip',
    'Billing City',
    'Billing State',
    'Billing Gender',
    'Billing Neighborhood',
    'Shipping First Name',
    'Shipping Last Name',
    'Shipping Street',
    'Shipping Country',
    'Shipping Zip',
    'Shipping City',
    'Shipping State',
    'Merchant Application Tax Id',
    'Merchant Application Name',
    'Merchant Application Account First Name',
    'Merchant Application Account Last Name',
    'Merchant Application Account Middle Name',
    'Merchant Application Account Street Name',
    'Merchant Application Account City',
    'Merchant Application Account Country',
    'Merchant Application Account State',
    'Merchant Application Account Zip',
    'Merchant Application Account Phone',
    'Merchant Application DBA',
    'Merchant Application BIN',
    'Merchant Application WEBSITE',
    'Merchant Application Business Type',
    'Payment Type Credit Card',
    'Payment Type PayPal',
    'Payment Type ACH',
    'Payment Type Bitcoin',
    'Merchant Application Bank Account Type',
    'Merchant Application MCC',
    'Merchant Application GIIN',
    'Merchant Application Group',
    'Customer Longitude',
    'Customer Latitude',
    'Browser Language',
    'Affiliate Id',
    'Affiliate Signup Date',
    'Account Phone',
    'Mobile Phone',
    'Work Phone',
    'Transaction Date Time',
    'Transaction Id',
    'Credit Card Number',
    'Credit Card Token',
    'Credit Card Type',
    'Payment Identifier Hash',
    'Payment Identifier Token',
    'ACH Account Unique Identifier',
    'Cryptocurrency Address',
    'Policy Profile',
    'Sub Merchant Name',
    'Merchant Identifier',
    'User Account Creation Date Time',
    'Digital Currency Addresses',
    'Destination Digital Currency Addresses',
    'Digital Currency Transaction Hash',
    'Tags',
    'Order Items',
    'Fraud Reason',
    'PayPal Payer Email',
    'PayPal Payer Id',
    'PayPal Payer Status',
    'PayPal Confirmed Address',
    'Destination Man',
    'Destination Email',
    'Destination Phone',
    'Destination Credit Card Number',
    'Destination Credit Card Token',
    'Destination Payment Identifier Hash',
    'Destination PayPal Payer Email',
    'Destination PayPal Payer Id',
    'Destination Payment Identifier Token',
    'Destination ACH HASH',
    'Destination Cryptocurrency Address',
    'Amount',
    'Currency',
    'Transaction Moto',
    'Gateway Name',
    'Document Front Side Image',
    'Document Back Side Image',
    'Face Image',
    'Application Stage',
    'Merchant Application Id',
    'Personal Guarantee',
    'Merchant Application Ownership',
    'Merchant Application Title',
    'Document Country',
    'Document Type',
    'Billing Date of Birth',
    'Social Security Number',
    'Additional SSN 1',
    'Additional SSN 2',
    'Last 4 Digits Additional SSN',
    'Sub Merchant Id',
    'AVS Result',
    'Error Code',
    'Auth Response',
    'Auth Code',
    'CVV Result',
    'Auth Response Text',
    'Graph Score Response',
    'Memo',
    'Memo 1',
    'Memo 2',
    'Memo 3',
    'Memo 4',
    'Memo 5',
    'Memo 6',
    'Memo 7',
    'Memo 8',
    'Memo 9',
    'Memo 10',
    'Memo 11',
    'Memo 12',
    'Memo 13',
    'Memo 14',
    'Memo 15',
    'Memo 16',
    'Memo 17',
    'Memo 18',
    'Memo 19',
    'Memo 20',
    'Memo 21',
    'Memo 22',
    'Memo 23',
    'Memo 24',
    'Memo 25',
    'Memo 26',
    'Memo 27',
    'Memo 28',
    'Memo 29',
    'Memo 30',
    'Memo 31',
    'Memo 32',
    'Memo 33',
    'Memo 34',
    'Memo 35',
    'Memo 36',
    'Memo 37',
    'Memo 38',
    'Memo 39',
    'Memo 40',
    'Memo 41',
    'Memo 42',
    'Memo 43',
    'Memo 44',
    'Memo 45',
    'Memo 46',
    'Memo 47',
    'Memo 48',
    'Memo 49',
    'Memo 50',
    'Memo 51',
    'Memo 52',
    'Memo 53',
    'Memo 54',
    'Memo 55',
    'Memo 56',
    'Memo 57',
    'Memo 58',
    'Memo 59',
    'Memo 60',
    'Memo 61',
    'Memo 62',
    'Memo 63',
    'Memo 64',
    'Memo 65',
    'Memo 66',
    'Memo 67',
    'Memo 68',
    'Memo 69',
    'Memo 70',
    'Memo 71',
    'Memo 72',
    'Memo 73',
    'Memo 74',
    'Memo 75',
    'Memo 76',
    'Memo 77',
    'Memo 78',
    'Memo 79',
    'Memo 80',
    'Memo 81',
    'Memo 82',
    'Memo 83',
    'Memo 84',
    'Memo 85',
    'Memo 86',
    'Memo 87',
    'Memo 88',
    'Memo 89',
    'Memo 90',
    'Memo 91',
    'Memo 92',
    'Memo 93',
    'Memo 94',
    'Memo 95',
    'Memo 96',
    'Memo 97',
    'Memo 98',
    'Memo 99'
]

ALPHABET = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U',
            'V', 'W', 'X', 'Y', 'Z']
