# Generated by Django 2.2.4 on 2019-09-17 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_date', models.DateTimeField(blank=True, null=True)),
                ('ending_data', models.DateTimeField(blank=True, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid_validation', models.CharField(blank=True, max_length=255, null=True)),
                ('pid_upload', models.CharField(blank=True, max_length=255, null=True)),
                ('starting_tine', models.DateTimeField(blank=True, null=True)),
                ('updating_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('completion_percentage', models.FloatField(blank=True, null=True)),
                ('num_successful_reg', models.IntegerField(blank=True, null=True)),
                ('num_failed_reg', models.IntegerField(blank=True, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('api_user', models.CharField(blank=True, max_length=255, null=True)),
                ('api_token', models.CharField(blank=True, max_length=255, null=True)),
                ('environment', models.CharField(choices=[('sbx', 'Sandbox'), ('stg', 'Staging'), ('qar', 'QAR API'), ('qa58', 'QA58')], max_length=255)),
                ('id_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poc.Status')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, upload_to='uploads/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('num_column', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poc.Process')),
            ],
        ),
    ]
