# Generated by Django 2.2.4 on 2019-09-23 03:48

import django.core.files.storage
from django.db import migrations, models
from mysite import settings


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=settings.PRIVATE_STORAGE_ROOT), upload_to=''),
        ),
    ]
