# Generated by Django 2.2.4 on 2019-09-26 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poc', '0002_auto_20190923_0348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[('process-table', 'Process Table'), ('account-setup', 'Account Setup'), ('file-upload', 'File Upload'), ('column-mapping', 'Column Mapping'), ('editing-data', 'Editing Data'), ('data-validation', 'Data Validation'), ('submit-correct-data', 'Schedule Job')], default='process-table', max_length=255)),
                ('initial_date', models.DateTimeField(blank=True, null=True)),
                ('ending_data', models.DateTimeField(blank=True, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Step',
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.RenameField(
            model_name='process',
            old_name='starting_tine',
            new_name='starting_time',
        ),
        migrations.AddField(
            model_name='file',
            name='filename_editing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='filename_original',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='filename_validated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='used_column_mapping',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ProcessHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_user', models.CharField(blank=True, max_length=255, null=True)),
                ('header_system', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_date', models.DateTimeField(blank=True, null=True)),
                ('ending_data', models.DateTimeField(blank=True, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('id_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poc.Process')),
            ],
            options={
                'verbose_name': 'Headers',
                'verbose_name_plural': 'Headers',
            },
        ),
        migrations.AddField(
            model_name='process',
            name='id_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='poc.ProcessStep'),
        ),
    ]
